#pragma once
#include <string>
#include <cstring>

namespace mm_rec {

struct ShaderData {
    const char* data;
    size_t length;
};

// Extern declarations for symbols generated by `ld -r -b binary`
// Symbol format: _binary_<filename_with_underscores>_start
// Path prefix is removed by CMake build rule
#define DECLARE_SHADER(NAME) \
    extern "C" char _binary_##NAME##_spv_start[]; \
    extern "C" char _binary_##NAME##_spv_end[];

DECLARE_SHADER(matmul)
DECLARE_SHADER(matmul_vec4)
DECLARE_SHADER(matmul_16x16)
DECLARE_SHADER(matmul_2x2)
DECLARE_SHADER(matmul_32x32)
DECLARE_SHADER(matmul_4x4)
DECLARE_SHADER(matmul_8x8)
DECLARE_SHADER(matmul_fp16)
DECLARE_SHADER(matmul_packed)
DECLARE_SHADER(matmul_prefetch)
DECLARE_SHADER(matmul_regblock)
DECLARE_SHADER(matmul_subgroup)

class EmbeddedShaders {
public:
    static ShaderData get(const std::string& name) {
        // Strip path prefix if present
        std::string filename = name;
        size_t lastSlash = filename.find_last_of("/\\");
        if (lastSlash != std::string::npos) {
            filename = filename.substr(lastSlash + 1);
        }

#define CHECK_SHADER(NAME) \
        if (filename == #NAME ".spv") \
            return {_binary_##NAME##_spv_start, \
                   (size_t)(_binary_##NAME##_spv_end - _binary_##NAME##_spv_start)};

        CHECK_SHADER(matmul)
        CHECK_SHADER(matmul_vec4)
        CHECK_SHADER(matmul_16x16)
        CHECK_SHADER(matmul_2x2)
        CHECK_SHADER(matmul_32x32)
        CHECK_SHADER(matmul_4x4)
        CHECK_SHADER(matmul_8x8)
        CHECK_SHADER(matmul_fp16)
        CHECK_SHADER(matmul_packed)
        CHECK_SHADER(matmul_prefetch)
        CHECK_SHADER(matmul_regblock)
        CHECK_SHADER(matmul_subgroup)

        return {nullptr, 0};
    }
};

} // namespace mm_rec
