#pragma once

#include <string>
#include <string_view>

extern "C" {
    // Symbols generated by ld -r -b binary
    // Naming convention: _binary_<filename>_start/end
    // Special chars like '.' are replaced by '_'
    
    extern const char _binary_index_html_start[];
    extern const char _binary_index_html_end[];
    
    extern const char _binary_style_css_start[];
    extern const char _binary_style_css_end[];
    
    extern const char _binary_app_js_start[];
    extern const char _binary_app_js_end[];
}

namespace mm_rec {
namespace assets {

inline std::string_view get_index_html() {
    return std::string_view(_binary_index_html_start, _binary_index_html_end - _binary_index_html_start);
}

inline std::string_view get_style_css() {
    return std::string_view(_binary_style_css_start, _binary_style_css_end - _binary_style_css_start);
}

inline std::string_view get_app_js() {
    return std::string_view(_binary_app_js_start, _binary_app_js_end - _binary_app_js_start);
}

} // namespace assets
} // namespace mm_rec
